<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConsultationSeeder extends Seeder
{
    public function run(): void
    {
        $dossierId = fn(string $num) => DB::table('dossiers_medicaux')->where('numero_dossier', $num)->value('id');
        $medecinId = fn(string $mat) => DB::table('medecins')->where('matricule', $mat)->value('id');

        $consultations = [
            // ── Patient 1 : HTA ────────────────────────────────────────────
            [
                'dossier_medical_id'       => $dossierId('DOS-2024-001'),
                'medecin_id'               => $medecinId('MED-2024-001'),
                'date'                     => '2024-10-05 09:15:00',
                'motif'                    => 'Contrôle hypertension artérielle',
                'diagnostic'               => 'HTA bien contrôlée sous traitement. Continuer Amlodipine 5mg.',
                'notes'                    => 'Patient asymptomatique. Observance correcte.',
                'tension'                  => '135/85',
                'poids'                    => 78.0,
                'temperature'              => 36.8,
                'frequence_cardiaque'      => 72,
                'glycemie'                 => null,
                'type_consultation'        => 'presentiel',
                'taille'                   => 175.0,
                'imc'                      => 25.5,
                'saturation_oxygene'       => 98.0,
                'frequence_respiratoire'   => '16',
                'examen_clinique'          => 'Auscultation cardio-pulmonaire normale. Pas d\'œdème.',
                'antecedents_signales'     => 'HTA, allergie pénicilline',
                'allergies_signalees'      => 'Pénicilline',
                'traitement_en_cours'      => 'Amlodipine 5mg/jour',
                'est_enceinte'             => false,
                'urgence'                  => 'faible',
                'recommandations'          => 'Continuer traitement. Réduire sel. Activité physique modérée.',
                'prochain_rdv'             => '2025-01-05',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],
            [
                'dossier_medical_id'       => $dossierId('DOS-2024-001'),
                'medecin_id'               => $medecinId('MED-2024-001'),
                'date'                     => '2025-03-01 16:10:00',
                'motif'                    => 'Renouvellement ordonnance - HTA',
                'diagnostic'               => 'HTA stable. Renouvellement traitement.',
                'notes'                    => 'Téléconsultation. Patient rapporte une bonne tolérance au traitement.',
                'tension'                  => '130/82',
                'poids'                    => 77.5,
                'temperature'              => null,
                'frequence_cardiaque'      => 70,
                'glycemie'                 => null,
                'type_consultation'        => 'teleconsultation',
                'taille'                   => 175.0,
                'imc'                      => 25.3,
                'saturation_oxygene'       => null,
                'frequence_respiratoire'   => null,
                'examen_clinique'          => 'Examen clinique non réalisé (téléconsultation).',
                'antecedents_signales'     => 'HTA connue',
                'allergies_signalees'      => 'Pénicilline',
                'traitement_en_cours'      => 'Amlodipine 5mg/jour',
                'est_enceinte'             => false,
                'urgence'                  => 'faible',
                'recommandations'          => 'Renouvellement ordonnance. Prochain bilan dans 3 mois.',
                'prochain_rdv'             => '2026-04-10',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],

            // ── Patient 3 : Diabète + HTA ──────────────────────────────────
            [
                'dossier_medical_id'       => $dossierId('DOS-2024-003'),
                'medecin_id'               => $medecinId('MED-2024-001'),
                'date'                     => '2024-11-20 08:20:00',
                'motif'                    => 'Bilan diabète et tension artérielle',
                'diagnostic'               => 'Diabète type 2 déséquilibré. HTA. Adapter traitement.',
                'notes'                    => 'Glycémie élevée. Patient peu observant au régime.',
                'tension'                  => '150/95',
                'poids'                    => 90.0,
                'temperature'              => 37.0,
                'frequence_cardiaque'      => 82,
                'glycemie'                 => 2.1,
                'type_consultation'        => 'presentiel',
                'taille'                   => 170.0,
                'imc'                      => 31.1,
                'saturation_oxygene'       => 97.0,
                'frequence_respiratoire'   => '18',
                'examen_clinique'          => 'Obésité abdominale. Pouls réguliers. Pas de neuropathie évidente.',
                'antecedents_signales'     => 'Diabète type 2, HTA, allergie sulfamides',
                'allergies_signalees'      => 'Sulfamides',
                'traitement_en_cours'      => 'Metformine 500mg x2/jour, Amlodipine 5mg',
                'est_enceinte'             => false,
                'urgence'                  => 'moyenne',
                'recommandations'          => 'Augmenter Metformine à 1000mg. Régime diabétique strict. Bilan lipidique.',
                'prochain_rdv'             => '2025-02-20',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],

            // ── Patient 4 : Paludisme ───────────────────────────────────────
            [
                'dossier_medical_id'       => $dossierId('DOS-2024-004'),
                'medecin_id'               => $medecinId('MED-2024-001'),
                'date'                     => '2025-02-10 09:45:00',
                'motif'                    => 'Fièvre, maux de tête, frissons depuis 2 jours',
                'diagnostic'               => 'Paludisme confirmé (test TDR positif). Paludisme simple non compliqué.',
                'notes'                    => 'TDR Plasmodium falciparum positif. Pas de signes de gravité.',
                'tension'                  => '110/70',
                'poids'                    => 65.0,
                'temperature'              => 39.2,
                'frequence_cardiaque'      => 95,
                'glycemie'                 => null,
                'type_consultation'        => 'presentiel',
                'taille'                   => 168.0,
                'imc'                      => 23.0,
                'saturation_oxygene'       => 98.0,
                'frequence_respiratoire'   => '20',
                'examen_clinique'          => 'Fièvre à 39,2°C. Légère splénomégalie. Pas de signe de neuropaludisme.',
                'antecedents_signales'     => 'Aucun antécédent',
                'allergies_signalees'      => null,
                'traitement_en_cours'      => null,
                'est_enceinte'             => false,
                'urgence'                  => 'moyenne',
                'recommandations'          => 'Coartem pendant 3 jours. Repos. Bonne hydratation. Revenir si aggravation.',
                'prochain_rdv'             => '2025-02-17',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],

            // ── Patient 5 : Cardiologie ─────────────────────────────────────
            [
                'dossier_medical_id'       => $dossierId('DOS-2024-005'),
                'medecin_id'               => $medecinId('MED-2024-003'),
                'date'                     => '2024-12-02 14:20:00',
                'motif'                    => 'Douleur thoracique intermittente, dyspnée d\'effort',
                'diagnostic'               => 'Angor stable. Ajustement traitement. ECG à faire.',
                'notes'                    => 'Patient avec antécédent de bypass. Douleur à l\'effort. ECG normal au repos.',
                'tension'                  => '145/90',
                'poids'                    => 72.0,
                'temperature'              => 36.9,
                'frequence_cardiaque'      => 68,
                'glycemie'                 => null,
                'type_consultation'        => 'presentiel',
                'taille'                   => 168.0,
                'imc'                      => 25.5,
                'saturation_oxygene'       => 96.0,
                'frequence_respiratoire'   => '16',
                'examen_clinique'          => 'Auscultation : quelques crépitants bases. ECG : rythme sinusal, pas de sus-ST.',
                'antecedents_signales'     => 'Cardiopathie ischémique, bypass 2019, cholestérol',
                'allergies_signalees'      => 'Aspirine forte dose',
                'traitement_en_cours'      => 'Aspirine 100mg, Atorvastatine 40mg, Ramipril 5mg',
                'est_enceinte'             => false,
                'urgence'                  => 'haute',
                'recommandations'          => 'Ajouter Métoprolol 25mg. Écho cardiaque. Bilan lipidique urgent.',
                'prochain_rdv'             => '2025-01-15',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],

            // ── Patient 6 : Gynécologie ─────────────────────────────────────
            [
                'dossier_medical_id'       => $dossierId('DOS-2024-006'),
                'medecin_id'               => $medecinId('MED-2024-004'),
                'date'                     => '2025-01-15 11:15:00',
                'motif'                    => 'Suivi post-opératoire et demande de contraception',
                'diagnostic'               => 'Bonne évolution post-césarienne. Mise sous pilule contraceptive.',
                'notes'                    => 'Cicatrice correcte. Utérus bien involutif. Désire contraception orale.',
                'tension'                  => '115/75',
                'poids'                    => 62.0,
                'temperature'              => 36.7,
                'frequence_cardiaque'      => 74,
                'glycemie'                 => null,
                'type_consultation'        => 'presentiel',
                'taille'                   => 165.0,
                'imc'                      => 22.8,
                'saturation_oxygene'       => 99.0,
                'frequence_respiratoire'   => '14',
                'examen_clinique'          => 'Abdomen souple. Cicatrice Pfannenstiel propre. Examen gynécologique normal.',
                'antecedents_signales'     => 'Césarienne 2022',
                'allergies_signalees'      => null,
                'traitement_en_cours'      => null,
                'est_enceinte'             => false,
                'urgence'                  => 'faible',
                'recommandations'          => 'Pilule microprogestative. Frottis cervical dans 6 mois.',
                'prochain_rdv'             => '2025-07-15',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],

            // ── Patient 2 : Asthme ──────────────────────────────────────────
            [
                'dossier_medical_id'       => $dossierId('DOS-2024-002'),
                'medecin_id'               => $medecinId('MED-2024-002'),
                'date'                     => '2024-10-12 10:45:00',
                'motif'                    => 'Crise d\'asthme légère, toux nocturne',
                'diagnostic'               => 'Asthme léger intermittent. Optimisation traitement.',
                'notes'                    => 'Crise légère depuis 3 jours. Bonne réponse aux bronchodilatateurs.',
                'tension'                  => '118/72',
                'poids'                    => 58.0,
                'temperature'              => 37.1,
                'frequence_cardiaque'      => 88,
                'glycemie'                 => null,
                'type_consultation'        => 'presentiel',
                'taille'                   => 162.0,
                'imc'                      => 22.1,
                'saturation_oxygene'       => 95.0,
                'frequence_respiratoire'   => '22',
                'examen_clinique'          => 'Sibilants bilatéraux à l\'auscultation. Pas de tirage.',
                'antecedents_signales'     => 'Asthme léger',
                'allergies_signalees'      => null,
                'traitement_en_cours'      => 'Salbutamol à la demande',
                'est_enceinte'             => false,
                'urgence'                  => 'moyenne',
                'recommandations'          => 'Salbutamol 2 bouffées toutes les 4-6h. Béclométasone inhalée si persistance.',
                'prochain_rdv'             => '2025-01-12',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],
        ];

        DB::table('consultations')->insert($consultations);
    }
}
